// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.28;

// Auto-generated by cdm install. Do not edit by hand.
// CDM package: @dw3labs/rainbow-leaderboard
// CDM version: 1

struct LeaderboardScoreClaim {
    address player;
    uint64 gameId;
    uint64 score;
    uint64 epoch;
    uint32 k;
    bytes32 rulesHash;
    uint64 expiry;
}

interface IDw3labsRainbowLeaderboard {
    error BadAttestation();
    error EpochInFuture();
    error Expired();
    error GameAlreadyRegistered();
    error InvalidShortString();
    error NotAnImprovement();
    error OwnableInvalidOwner(address owner);
    error OwnableUnauthorizedAccount(address account);
    error RulesMismatch();
    error SessionAlreadyUsed();
    error SessionIndexOutOfRange();
    error StringTooLong(string str);
    error UnknownGame();
    error ZeroRulesHash();
    event EIP712DomainChanged();
    event GameRegistered(uint64 indexed gameId, bytes32 rulesHash);
    event NewBest(uint64 indexed gameId, address indexed player, uint64 score, bytes32 sessionId, uint64 epoch);
    event OwnershipTransferred(address indexed previousOwner, address indexed newOwner);
    event VerifierSet(address indexed verifier, bool allowed);
    function best(uint64 gameId, address player) external view returns (uint64);
    function currentEpoch() external view returns (uint64);
    function eip712Domain() external view returns (bytes1, string memory, string memory, uint256, address, bytes32, uint256[] memory);
    function epochSeconds() external view returns (uint64);
    function gameRules(uint64 gameId) external view returns (bytes32);
    function isVerifier(address verifier) external view returns (bool);
    function maxSessionsPerEpoch() external view returns (uint32);
    function owner() external view returns (address);
    function registerGame(uint64 gameId, bytes32 rulesHash) external;
    function renounceOwnership() external;
    function scoreDigest(LeaderboardScoreClaim calldata c) external view returns (bytes32);
    function sessionIdFor(address player, uint64 epoch, uint32 k) external pure returns (bytes32);
    function setVerifier(address verifier, bool allowed) external;
    function submit(LeaderboardScoreClaim calldata c, bytes calldata signature) external;
    function transferOwnership(address newOwner) external;
    function usedSession(bytes32 sessionId) external view returns (bool);
}

library Dw3labsRainbowLeaderboard {
    address internal constant ADDRESS = 0x9cc62a70E0d2ed75432C3d9c1F997a122eE976a0;

    function ref() internal pure returns (IDw3labsRainbowLeaderboard) {
        return IDw3labsRainbowLeaderboard(ADDRESS);
    }

    function cdm() internal pure returns (IDw3labsRainbowLeaderboard) {
        return ref();
    }
}
