// Auto-generated by cdm install -- do not edit
import type { HexString, SizedHex } from "polkadot-api";

declare module "@parity/product-sdk-contracts" {
    interface Contracts {
        "@dw3labs/rainbow-leaderboard": {
            methods: {
                best: { args: [gameId: bigint, player: HexString]; response: bigint };
                board: { args: [gameId: bigint, offset: bigint, limit: bigint]; response: { players: HexString[]; scores: bigint[] } };
                currentDay: { args: []; response: bigint };
                currentEpoch: { args: []; response: bigint };
                dailyBest: { args: [gameId: bigint, day: bigint, player: HexString]; response: bigint };
                dailyBoard: { args: [gameId: bigint, day: bigint, offset: bigint, limit: bigint]; response: { players: HexString[]; scores: bigint[] } };
                dailyPlayerCount: { args: [gameId: bigint, day: bigint]; response: bigint };
                dayOf: { args: [epoch: bigint]; response: bigint };
                eip712Domain: { args: []; response: { fields: SizedHex<1>; name: string; version: string; chainId: bigint; verifyingContract: HexString; salt: SizedHex<32>; extensions: bigint[] } };
                epochSeconds: { args: []; response: bigint };
                gameRules: { args: [gameId: bigint]; response: SizedHex<32> };
                isVerifier: { args: [verifier: HexString]; response: boolean };
                maxSessionsPerEpoch: { args: []; response: number };
                owner: { args: []; response: HexString };
                playerCount: { args: [gameId: bigint]; response: bigint };
                registerGame: { args: [gameId: bigint, rulesHash: SizedHex<32>]; response: undefined };
                renounceOwnership: { args: []; response: undefined };
                scoreDigest: { args: [c: { player: HexString; gameId: bigint; score: bigint; epoch: bigint; k: number; rulesHash: SizedHex<32>; expiry: bigint }]; response: SizedHex<32> };
                sessionIdFor: { args: [player: HexString, epoch: bigint, k: number]; response: SizedHex<32> };
                setVerifier: { args: [verifier: HexString, allowed: boolean]; response: undefined };
                submit: { args: [c: { player: HexString; gameId: bigint; score: bigint; epoch: bigint; k: number; rulesHash: SizedHex<32>; expiry: bigint }, signature: Uint8Array]; response: undefined };
                transferOwnership: { args: [newOwner: HexString]; response: undefined };
                usedSession: { args: [sessionId: SizedHex<32>]; response: boolean };
            };
        };
    }
}
